//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwaySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Phone
    {
        public int Employee_ID { get; set; }
        public int Code { get; set; }
        public int Number { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
