//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwaySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Employee_Phone = new HashSet<Employee_Phone>();
            this.Tickets = new HashSet<Ticket>();
            this.Trains = new HashSet<Train>();
            this.Trains1 = new HashSet<Train>();
            this.Trips = new HashSet<Trip>();
            this.USERs = new HashSet<USER>();
        }
    
        public int ID { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public int Age { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public int Salary { get; set; }
        public int Working_Hours { get; set; }
        public int JobID { get; set; }
        public Nullable<int> StationID { get; set; }
    
        public virtual Employee_Contact Employee_Contact { get; set; }
        public virtual ICollection<Employee_Phone> Employee_Phone { get; set; }
        public virtual Job Job { get; set; }
        public virtual Station Station { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<Train> Trains { get; set; }
        public virtual ICollection<Train> Trains1 { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
        public virtual ICollection<USER> USERs { get; set; }
    }
}
