//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwaySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public Passenger()
        {
            this.Passenger_Contact = new HashSet<Passenger_Contact>();
            this.Passenger_Phone = new HashSet<Passenger_Phone>();
            this.Passenger_Subscription = new HashSet<Passenger_Subscription>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int ID { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
    
        public virtual ICollection<Passenger_Contact> Passenger_Contact { get; set; }
        public virtual ICollection<Passenger_Phone> Passenger_Phone { get; set; }
        public virtual ICollection<Passenger_Subscription> Passenger_Subscription { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
