//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwaySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger_Subscription
    {
        public int Passenger_ID { get; set; }
        public int Subscription_ID { get; set; }
        public System.DateTime Exp_Date { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
