//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwaySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.Trips = new HashSet<Trip>();
        }
    
        public int Source_ID { get; set; }
        public int Destination_ID { get; set; }
        public int Distance { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
