//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwaySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public Station()
        {
            this.Coach_Yard = new HashSet<Coach_Yard>();
            this.Employees = new HashSet<Employee>();
            this.Repair_Yard = new HashSet<Repair_Yard>();
            this.Routes = new HashSet<Route>();
            this.Routes1 = new HashSet<Route>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int Street { get; set; }
    
        public virtual ICollection<Coach_Yard> Coach_Yard { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Repair_Yard> Repair_Yard { get; set; }
        public virtual ICollection<Route> Routes { get; set; }
        public virtual ICollection<Route> Routes1 { get; set; }
    }
}
