//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwaySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public Subscription()
        {
            this.Passenger_Subscription = new HashSet<Passenger_Subscription>();
        }
    
        public int ID { get; set; }
        public int Fees { get; set; }
        public string Class { get; set; }
        public int No_Trips { get; set; }
    
        public virtual ICollection<Passenger_Subscription> Passenger_Subscription { get; set; }
    }
}
