//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwaySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public string Class { get; set; }
        public int Price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Booking_Clerk_ID { get; set; }
        public Nullable<int> Passenger_ID { get; set; }
        public int Trip_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Passenger Passenger { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
