//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwaySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        public Train()
        {
            this.Trips = new HashSet<Trip>();
        }
    
        public int ID { get; set; }
        public string Model { get; set; }
        public bool Status { get; set; }
        public string Color { get; set; }
        public int No_Seats { get; set; }
        public int Speed { get; set; }
        public int No_Cars { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Driver_ID { get; set; }
        public Nullable<int> Repair_Yard_ID { get; set; }
        public Nullable<int> Coach_Yard_ID { get; set; }
        public Nullable<int> BoughtByID { get; set; }
    
        public virtual Coach_Yard Coach_Yard { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Repair_Yard Repair_Yard { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
