//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwaySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public Trip()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int ID { get; set; }
        public System.DateTime Dept_Time { get; set; }
        public System.DateTime Arr_Time { get; set; }
        public int Type { get; set; }
        public int Source_ID { get; set; }
        public int Destintaion_ID { get; set; }
        public int Train_ID { get; set; }
        public Nullable<int> StManager_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Route Route { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual Train Train { get; set; }
    }
}
