//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwaySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public byte[] PasswordHash { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<System.Guid> Salt { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
